#!/usr/bin/env bash
# Regenerate the roadmap progress block in README.md from docs/ROADMAP.md.
#
# A task row is any markdown table row whose first cell is a dotted task ID
# (e.g. "0.1.1", "8.4", "10.9"). A task counts as done when its Notes cell
# contains the string "✅ Done".
#
# Updates the block delimited by:
#   <!-- progress:start -->
#   <!-- progress:end -->
# in README.md. Idempotent.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROADMAP="$REPO_ROOT/docs/ROADMAP.md"
README="$REPO_ROOT/README.md"

[[ -f "$ROADMAP" ]] || { echo "missing $ROADMAP" >&2; exit 1; }
[[ -f "$README"  ]] || { echo "missing $README"  >&2; exit 1; }

block="$(awk '
  function bar(pct,    n, i, s) {
    n = int(pct / 5 + 0.5)
    s = ""
    for (i = 0; i < 20; i++) s = s (i < n ? "▓" : "░")
    return s
  }
  /^## Phase [0-9]+/ {
    s = $0
    sub(/^## Phase /, "", s)
    colon = index(s, ":")
    cur_num = substr(s, 1, colon - 1) + 0
    cur_title = substr(s, colon + 1)
    sub(/^[[:space:]]+/, "", cur_title)
    sub(/[[:space:]]*\([Mm][0-9]+\)[[:space:]]*$/, "", cur_title)
    sub(/[[:space:]]*\(Initial commit\)[[:space:]]*$/, "", cur_title)
    sub(/[[:space:]]*\(Deferred\)[[:space:]]*$/, " (deferred)", cur_title)
    sub(/[[:space:]]*\(Long-term\)[[:space:]]*$/, " (long-term)", cur_title)
    if (!(cur_num in seen)) { order[++n] = cur_num; seen[cur_num] = 1 }
    title[cur_num] = cur_title
    next
  }
  /^\| [0-9]+\.[0-9]+(\.[0-9]+)?[[:space:]]+\|/ {
    total[cur_num]++
    grand_total++
    if (index($0, "✅ Done")) { done[cur_num]++; grand_done++ }
  }
  END {
    pct = grand_total ? grand_done * 100.0 / grand_total : 0
    printf "**Overall:** %d / %d tasks complete (%.1f%%)\n\n", grand_done, grand_total, pct
    printf "`%s` %.1f%%\n\n", bar(pct), pct
    print  "| Phase | Title | Done | Total | % |"
    print  "| ----- | ----- | ---- | ----- | - |"
    for (i = 1; i <= n; i++) {
      p = order[i]
      d = done[p] + 0
      t = total[p] + 0
      pp = t ? d * 100.0 / t : 0
      printf "| %d | %s | %d | %d | %.1f%% |\n", p, title[p], d, t, pp
    }
    printf "\n_Regenerated by `scripts/roadmap-progress.sh` from `docs/ROADMAP.md` — a task row counts as done when its Notes cell contains ✅ Done._\n"
  }
' "$ROADMAP")"

start_marker="<!-- progress:start -->"
end_marker="<!-- progress:end -->"

if ! grep -qF "$start_marker" "$README"; then
  echo "README is missing $start_marker / $end_marker — add the block first" >&2
  exit 2
fi

tmp="$(mktemp)"
awk -v block="$block" -v s="$start_marker" -v e="$end_marker" '
  $0 == s { print; print block; in_block = 1; next }
  $0 == e { in_block = 0; print; next }
  !in_block { print }
' "$README" > "$tmp"
mv "$tmp" "$README"

echo "Updated $README"
